### ISSUE TITLE
Support of iPhone 15 Series

### ISSUE THREAD

**Issue by howg0924** [chlee1001/react-native-iphone-screen-helper#5]
Thank you so much for maintaining this useful package.

As iPhone 15 series will be released soon, when will we know the screen resolution of these new iPhones so we can keep this library to work correctly? Does the current Xcode beta give any hint?

Thank you.

**Comment by chlee1001** [comment]
Thank you for your interest.
I'm also looking for screen size information for the iPhone 15 series. However, I don't think I know the exact information yet, and I think I'll know after the official release (September 14).
I will update you when I know the exact information (about Safe Area Insets).

Thank you.

**Comment by howg0924** [comment]
@chlee1001 iPhone 15 is now officially announced. May we calculate the information we need based on the following screen spec? Though I'm not sure about the math.

[iPhone 15]
6.1‑inch (diagonal) all‑screen OLED display 2556‑by‑1179-pixel resolution at 460 ppi
[iPhone 15 Plus]
6.7‑inch (diagonal) all‑screen OLED display 2796‑by‑1290-pixel resolution at 460 ppi
[iPhone 15 Pro]
6.1‑inch (diagonal) all‑screen OLED display 2556‑by‑1179-pixel resolution at 460 ppi
[iPhone 15 Pro Max]
6.7‑inch (diagonal) all‑screen OLED display 2796‑by‑1290-pixel resolution at 460 ppi

**Comment by chlee1001** [comment]
Hello @howg0924

~Based on your feedback, I have made several enhancements to the project, including adding new features and conducting necessary refactorings.~

~I have just created a new pull request that implements these changes and I would be really grateful if you could take out some time to review the changes in this [#6 ](https://github.com/chlee1001/react-native-iphone-screen-helper/pull/6) and share your feedback with us.~

I haven't tried running the iPhone 15 series on xcode yet, so I haven't tested it.
However, it has a screen size and ppi similar to the iPhone 14 pro/promax with dynamic island, so I think it will be reflected as it is..

Thank you.
